steps:
- name: 'maven:3.6.0-jdk-8-alpine'
  args: ['mvn', 'clean', 'install', '-f', 'pom.xml']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tg_place_service:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tg_place_service:$SHORT_SHA']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - "run"
  - "--filename=deployment.yaml,service.yaml"
  - "--image=gcr.io/$PROJECT_ID/tg_place_service:$SHORT_SHA"
  - "--location=europe-west8"
  - "--cluster=tg-kube-cluster"
images:
- 'gcr.io/$PROJECT_ID/tg_place_service:$SHORT_SHA'
