apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-place-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-place-service
  template:
    metadata:
      labels:
        app: tg-place-service
    spec:
      containers:
      - name: tg-place-service
        image: gcr.io/tourguide-393611/tg_place_service
        ports:
        - containerPort: 8016
