apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-place-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-place-service
  template:
    metadata:
      labels:
        app: tg-place-service
    spec:
      containers:
      - name: tg-place-service
        image: gcr.io/tourguide-393611/tg-place-service
        ports:
        - containerPort: 8011
        volumeMounts:               # Add this section
        - name: place-config
          mountPath: /config       # You can choose the path where you want to mount it
      volumes:                      # Add this section
      - name: place-config
        configMap:
          name: place-config