name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: tourguide-393611
  GKE_CLUSTER: tg-kube-cluster
  GKE_ZONE: europe-southwest1
  DEPLOYMENT_NAME: tg-place-service
  CONTAINER: gcr.io/tourguide-393611/tg_place_service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud --quiet auth configure-docker

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
